# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: registration
  pool: 5
  reconnect: true
  username: root
  password: royalabadi
  host: 192.168.101.220
  #host: 127.0.0.1
  #port: 3307

jdeoracle:
  adapter: oracle_enhanced
  username: JDE
  password: jdevg920
  database: "(DESCRIPTION=(ADDRESS_LIST=(ADDRESS=(PROTOCOL=tcp)(HOST=192.212.212.54)(PORT=1521)))(CONNECT_DATA=(SERVICE_NAME=ORCL)))"
